export {flagRespostas, flagLinks}

const flagRespostas = {
    america: [
        "Argentina",
        "Brasil",
        "Canadá",
        "Colômbia",
        "Cuba",
        "Dominica",
        "Equador",
        "Estados Unidos",
        "Guiana Francesa",
        "Honduras",
        "Ilhas Malvinas",
        "México",
        "Paraguai",
        "República Dominicana",
        "Trindade e Tobago",
        "Uruguai",
        "Venezuela"
    ],

    asia: [
        "Afeganistão",
        "Azerbaijão",
        "Bahrein",
        "Bangladesh",
        "Brunei",
        "Butão",
        "Catar",
        "China",
        "Filipinas",
        "Geórgia",
        "Hong Kong",
        "Indonésia",
        "Israel",
        "Japão",
        "Nepal",
        "Omã",
        "Tailândia"
    ],
    
    europa: [
        "Alemanha",
        "Bélgica",
        "Bulgária",
        "Dinamarca",
        "Estônia",
        "Finlândia",
        "França",
        "Grécia",
        "Irlanda",
        "Islândia",
        "Itália",
        "Luxemburgo",
        "Noruega",
        "País de Gales",
        "Portugal",
        "República Tcheca",
        "Sérvia"
    ]
}

const flagLinks = {
    america: [
        "/public/images/bandeiras/america/argentina.png",
        "/public/images/bandeiras/america/brasil.png",
        "/public/images/bandeiras/america/canada.png",
        "/public/images/bandeiras/america/colombia.png",
        "/public/images/bandeiras/america/cuba.png",
        "/public/images/bandeiras/america/dominica.png",
        "/public/images/bandeiras/america/equador.png",
        "/public/images/bandeiras/america/estados-unidos.png",
        "/public/images/bandeiras/america/guiana-francesa.png",
        "/public/images/bandeiras/america/honduras.png",
        "/public/images/bandeiras/america/ilhas-malvinas.png",
        "/public/images/bandeiras/america/mexico.png",
        "/public/images/bandeiras/america/paraguai.png",
        "/public/images/bandeiras/america/republica-dominicana.png",
        "/public/images/bandeiras/america/trindade-tobago.png",
        "/public/images/bandeiras/america/uruguai.png",
        "/public/images/bandeiras/america/venezuela.png"
    ],
    asia: [
        "/public/images/bandeiras/asia/afeganistao.png",
        "/public/images/bandeiras/asia/azerbaijao.png",
        "/public/images/bandeiras/asia/bahrein.png",
        "/public/images/bandeiras/asia/bangladesh.png",
        "/public/images/bandeiras/asia/brunei.png",
        "/public/images/bandeiras/asia/butao.png",
        "/public/images/bandeiras/asia/catar.png",
        "/public/images/bandeiras/asia/china.png",
        "/public/images/bandeiras/asia/filipinas.png",
        "/public/images/bandeiras/asia/georgia.png",
        "/public/images/bandeiras/asia/hong-kong.png",
        "/public/images/bandeiras/asia/indonesia.png",
        "/public/images/bandeiras/asia/israel.png",
        "/public/images/bandeiras/asia/japao.png",
        "/public/images/bandeiras/asia/nepal.png",
        "/public/images/bandeiras/asia/oma.png",
        "/public/images/bandeiras/asia/tailandia.png"
    ],
    europa: [
        "/public/images/bandeiras/europa/alemanha.png",
        "/public/images/bandeiras/europa/belgica.png",
        "/public/images/bandeiras/europa/bulgaria.png",
        "/public/images/bandeiras/europa/dinamarca.png",
        "/public/images/bandeiras/europa/estonia.png",
        "/public/images/bandeiras/europa/finlandia.png",
        "/public/images/bandeiras/europa/franca.png",
        "/public/images/bandeiras/europa/grecia.png",
        "/public/images/bandeiras/europa/irlanda.png",
        "/public/images/bandeiras/europa/islandia.png",
        "/public/images/bandeiras/europa/italia.png",
        "/public/images/bandeiras/europa/luxemburgo.png",
        "/public/images/bandeiras/europa/noruega.png",
        "/public/images/bandeiras/europa/gales.png",
        "/public/images/bandeiras/europa/portugal.png",
        "/public/images/bandeiras/europa/rp-tcheca.png",
        "/public/images/bandeiras/europa/servia.png"
    ]
}